#!/bin/bash

checkPostgres () {
  if [[ $(id -u postgres 2> /dev/null) = "" ]]; then
    echo "Parece que o postgres não está instalado!";
    echo "Execute: sudo apt update && sudo apt install postgresql postgresql-contrib";
    exit;
  fi

  if [[ $(pgrep -u postgres -fa -- -D) = "" ]]; then
    echo "PostgreSQL não está sendo executado, tentando iniciar...";
    sudo service postgresql start;
  fi
}

createDatabase () {
  # sudo su -c "psql -c \"CREATE DATABASE $1\";" postgres;
  sudo -iu  postgres psql -c "CREATE DATABASE $1;"
}

destroyDatabase () {
  # sudo su -c "psql -c \"DROP DATABASE $1\";" postgres;
  sudo -iu  postgres psql -c "DROP DATABASE $1;"
}

runScripts () {
 
  for f in scripts/*; do
    echo "Executando script $f...$1 // $2";
    cp -r $2 /tmp/$1
    cd /tmp/$1
    # sudo su -c "psql -d $1 -f $f" postgres;
    sudo -iu postgres psql $1 -c "\i /tmp/$1/$f";
  done
}

enterPostgresCli () {
  # sudo su -c "psql -d $1" postgres;
  sudo -iu postgres psql $1;
}